name: Build dylib

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install clang
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm-dev libxml2-dev
          
      - name: Build dylib
        run: |
          clang -dynamiclib -arch arm64 \
            -fobjc-arc \
            -framework UIKit \
            -framework WebKit \
            -framework Foundation \
            -framework CoreGraphics \
            -framework QuartzCore \
            -undefined dynamic_lookup \
            -o FFMod.dylib make.dylib.m
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: FFMod
          path: FFMod.dylib
